# Generated by Django 5.1.4 on 2025-01-04 08:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(error_messages="Name can't be more than 255 characters", max_length=255)),
                ('last_name', models.CharField(error_messages="Name can't be more than 255 characters", max_length=255)),
                ('email', models.EmailField(error_messages='Email must be unique and valid', max_length=254, unique=True)),
                ('phone_number', models.CharField(error_messages='Phone number must be 11 digits', max_length=11)),
                ('instrument', models.CharField(choices=[('Guitar', 'Guitar'), ('Drum', 'Drum'), ('Flute', 'Flute')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=255)),
                ('release_date', models.DateField(auto_now_add=True)),
                ('rating', models.FloatField(validators=[django.core.validators.MaxValueValidator(5.0), django.core.validators.MinValueValidator(0.0)])),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musician.musician')),
            ],
        ),
    ]
